if (!window.__eduHubIndexContentTranslationMap) {
    window.__eduHubIndexContentTranslationMap = {
        "id_title_formulas": "id_title_formulas",
        "id_title_1": "id_title_1",
        "formula_name_1": "formula_name_1",
        "formula_desc_1": "formula_desc_1",
        "formula_example_1": "formula_example_1",
        "formula_name_2": "formula_name_2",
        "formula_desc_2": "formula_desc_2",
        "formula_example_2": "formula_example_2",
        "formula_name_3": "formula_name_3",
        "formula_desc_3": "formula_desc_3",
        "formula_example_3": "formula_example_3",
        "formula_name_4": "formula_name_4",
        "formula_desc_4": "formula_desc_4",
        "formula_example_4": "formula_example_4",
        "formula_name_5": "formula_name_5",
        "formula_desc_5": "formula_desc_5",
        "formula_example_5": "formula_example_5",

        "id_title_2": "id_title_2",
        "formula_name_pow_1": "formula_name_pow_1",
        "formula_desc_pow_1": "formula_desc_pow_1",
        "formula_example_pow_1": "formula_example_pow_1",
        "formula_name_pow_2": "formula_name_pow_2",
        "formula_desc_pow_2": "formula_desc_pow_2",
        "formula_example_pow_2": "formula_example_pow_2",
        "formula_name_pow_3": "formula_name_pow_3",
        "formula_desc_pow_3": "formula_desc_pow_3",
        "formula_example_pow_3": "formula_example_pow_3",
        "formula_name_pow_4": "formula_name_pow_4",
        "formula_desc_pow_4": "formula_desc_pow_4",
        "formula_example_pow_4": "formula_example_pow_4",
        "formula_name_pow_5": "formula_name_pow_5",
        "formula_desc_pow_5": "formula_desc_pow_5",
        "formula_example_pow_5": "formula_example_pow_5",

        "formula_name_root_1": "formula_name_root_1",
        "formula_desc_root_1": "formula_desc_root_1",
        "formula_example_root_1": "formula_example_root_1",
        "formula_name_root_2": "formula_name_root_2",
        "formula_desc_root_2": "formula_desc_root_2",
        "formula_example_root_2": "formula_example_root_2",
        "formula_name_root_3": "formula_name_root_3",
        "formula_desc_root_3": "formula_desc_root_3",
        "formula_example_root_3": "formula_example_root_3",
        "formula_name_root_4": "formula_name_root_4",
        "formula_desc_root_4": "formula_desc_root_4",
        "formula_example_root_4": "formula_example_root_4",
        "formula_name_root_5": "formula_name_root_5",
        "formula_desc_root_5": "formula_desc_root_5",
        "formula_example_root_5": "formula_example_root_5",

        "id_title_3":"id_title_3",
        "formula_name_alg_1": "formula_name_alg_1",
        "formula_desc_alg_1": "formula_desc_alg_1",
        "formula_example_alg_1": "formula_example_alg_1",
        "formula_name_alg_2": "formula_name_alg_2",
        "formula_desc_alg_2": "formula_desc_alg_2",
        "formula_example_alg_2": "formula_example_alg_2",
        "formula_name_alg_3": "formula_name_alg_3",
        "formula_desc_alg_3": "formula_desc_alg_3",
        "formula_example_alg_3": "formula_example_alg_3",
        "formula_name_alg_4": "formula_name_alg_4",
        "formula_desc_alg_4": "formula_desc_alg_4",
        "formula_example_alg_4": "formula_example_alg_4",

        "id_title_4": "id_title_4",
        "formula_name_geom_1": "formula_name_geom_1",
        "formula_desc_geom_1": "formula_desc_geom_1",
        "formula_example_geom_1": "formula_example_geom_1",
        "formula_name_geom_2": "formula_name_geom_2",
        "formula_desc_geom_2": "formula_desc_geom_2",
        "formula_example_geom_2": "formula_example_geom_2",
        "formula_name_geom_3": "formula_name_geom_3",
        "formula_desc_geom_3": "formula_desc_geom_3",
        "formula_example_geom_3": "formula_example_geom_3",
        "formula_name_geom_4": "formula_name_geom_4",
        "formula_desc_geom_4": "formula_desc_geom_4",
        "formula_example_geom_4": "formula_example_geom_4",
        "formula_name_geom_help_5": "formula_name_geom_help_5",
        "formula_desc_geom_help_5": "formula_desc_geom_help_5",
        "formula_example_geom_help_5": "formula_example_geom_help_5",

        "id_title_5": "id_title_5",
        "formula_name_geom_5": "formula_name_geom_5",
        "formula_desc_geom_5": "formula_desc_geom_5",
        "formula_example_geom_5": "formula_example_geom_5",
        "formula_name_geom_6": "formula_name_geom_6",
        "formula_desc_geom_6": "formula_desc_geom_6",
        "formula_example_geom_6": "formula_example_geom_6",
        "formula_name_geom_7": "formula_name_geom_7",
        "formula_desc_geom_7": "formula_desc_geom_7",
        "formula_example_geom_7": "formula_example_geom_7",
        "formula_name_geom_8": "formula_name_geom_8",
        "formula_desc_geom_8": "formula_desc_geom_8",
        "formula_example_geom_8": "formula_example_geom_8",
        "formula_name_geom_9": "formula_name_geom_9",
        "formula_desc_geom_9": "formula_desc_geom_9",
        "formula_example_geom_9": "formula_example_geom_9",
        "formula_name_geom_10": "formula_name_geom_10",
        "formula_desc_geom_10": "formula_desc_geom_10",
        "formula_example_geom_10": "formula_example_geom_10",
        "formula_name_geom_11": "formula_name_geom_11",
        "formula_desc_geom_11": "formula_desc_geom_11",
        "formula_example_geom_11": "formula_example_geom_11",

        "id_title_6": "id_title_6",
        "formula_name_geom_12": "formula_name_geom_12",
        "formula_desc_geom_12": "formula_desc_geom_12",
        "formula_example_geom_12": "formula_example_geom_12",
        "formula_name_geom_13": "formula_name_geom_13",
        "formula_desc_geom_13": "formula_desc_geom_13",
        "formula_example_geom_13": "formula_example_geom_13",
        "formula_name_geom_14": "formula_name_geom_14",
        "formula_desc_geom_14": "formula_desc_geom_14",
        "formula_example_geom_14": "formula_example_geom_14",
        "formula_name_geom_15": "formula_name_geom_15",
        "formula_desc_geom_15": "formula_desc_geom_15",
        "formula_example_geom_15": "formula_example_geom_15",

        "id_title_7": "id_title_7",
        "formula_name_poly_1": "formula_name_poly_1",
        "formula_desc_poly_1": "formula_desc_poly_1",
        "formula_example_poly_1": "formula_example_poly_1",
        "formula_name_poly_2": "formula_name_poly_2",
        "formula_desc_poly_2": "formula_desc_poly_2",
        "formula_example_poly_2": "formula_example_poly_2",
        "formula_name_poly_3": "formula_name_poly_3",
        "formula_desc_poly_3": "formula_desc_poly_3",
        "formula_example_poly_3": "formula_example_poly_3",
        "formula_name_poly_4": "formula_name_poly_4",
        "formula_desc_poly_4": "formula_desc_poly_4",
        "formula_example_poly_4": "formula_example_poly_4",
        "formula_name_poly_5": "formula_name_poly_5",
        "formula_desc_poly_5": "formula_desc_poly_5",
        "formula_example_poly_5": "formula_example_poly_5",
        "formula_name_poly_6": "formula_name_poly_6",
        "formula_desc_poly_6": "formula_desc_poly_6",
        "formula_example_poly_6": "formula_example_poly_6",
        "formula_name_poly_7": "formula_name_poly_7",
        "formula_desc_poly_7": "formula_desc_poly_7",
        "formula_example_poly_7": "formula_example_poly_7",
        "formula_name_poly_8": "formula_name_poly_8",
        "formula_desc_poly_8": "formula_desc_poly_8",
        "formula_example_poly_8": "formula_example_poly_8",
        "formula_name_poly_9": "formula_name_poly_9",
        "formula_desc_poly_9": "formula_desc_poly_9",
        "formula_example_poly_9": "formula_example_poly_9",

        "id_title_8": "id_title_8",
        "formula_name_poly_10": "formula_name_poly_10",
        "formula_desc_poly_10": "formula_desc_poly_10",
        "formula_example_poly_10": "formula_example_poly_10",
        "formula_name_poly_11": "formula_name_poly_11",
        "formula_desc_poly_11": "formula_desc_poly_11",
        "formula_example_poly_11": "formula_example_poly_11",
        "formula_name_poly_12": "formula_name_poly_12",
        "formula_desc_poly_12": "formula_desc_poly_12",
        "formula_example_poly_12": "formula_example_poly_12",
        "formula_name_poly_13": "formula_name_poly_13",
        "formula_desc_poly_13": "formula_desc_poly_13",
        "formula_example_poly_13": "formula_example_poly_13",
        "formula_name_poly_14": "formula_name_poly_14",
        "formula_desc_poly_14": "formula_desc_poly_14",
        "formula_example_poly_14": "formula_example_poly_14",
        "formula_name_poly_15": "formula_name_poly_15",
        "formula_desc_poly_15": "formula_desc_poly_15",
        "formula_example_poly_15": "formula_example_poly_15",
        "formula_name_poly_16": "formula_name_poly_16",
        "formula_desc_poly_16": "formula_desc_poly_16",
        "formula_example_poly_16": "formula_example_poly_16"
    };
}   
var contentTranslationMap = window.__eduHubIndexContentTranslationMap;

if (typeof window.updateContentLang !== 'function') {
    window.updateContentLang = function(lang) {
        selectLanguage(lang, contentTranslationMap, 'translations-path-page');
    };
}

function applySavedIndexLanguage() {
    setTimeout(() => {
        const savedLang = localStorage.getItem('selectedLang') || 'pl';
        selectLanguage(savedLang, contentTranslationMap, 'translations-path-page');
    }, 50);
}

if (!window.__eduHubIndexLangHandlersInitialized) {
    window.__eduHubIndexLangHandlersInitialized = true;

    window.addEventListener('load', applySavedIndexLanguage);
    window.addEventListener('pageshow', applySavedIndexLanguage);
}
